config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  get "/admin", to: "home#admin_panel", as: 'admin_panel'

  get "/profile/:id", to: "users#show", as: 'user_profile'
  get "/profile/:user_id/edit", to: "users#edit", as: 'edit_user_profile'

  post "/profile/:user_id/update", to: "users#update", as: 'update_user_profile'
  patch "/profile/:user_id/update_privacy", to: "users#update_privacy", as: 'update_user_privacy'
  get "/profiles", to: "users#index", as: 'user_profiles'
  get "/grapevine", to: "users#index", as: 'grapevine'

  get   "/users/:user_id/verify", to: "verification#edit"
  patch "/users/:user_id/verify", to: "verification#update", as: "verification"


  post '/posts/:post_id/comment', to: 'posts#comment', as: 'comment_post'
  get '/posts/hidden', to: 'posts#hidden', as: 'hidden_posts'
  post '/posts/:post_id/hide', to: 'posts#hide', as: 'hide_post'
  post '/posts/:post_id/unhide', to: 'posts#unhide', as: 'unhide_post'
  patch '/posts/:id/tags', to: 'posts#edit_tags', as: 'edit_post_tags'

  get "/users/upload", to: "users#upload", as: "upload_users"
  post "/users/import", to: "users#import"

  get 'tags/:tag', to: 'posts#index', as: :tag

  get "/users", to: "users#list", as: "list_users"

  devise_for :users
  resources :posts do
    get :autocomplete_tag_name, :on => :collection
  end

  resources :announcements
  resources :comments, only: [:update, :destroy]
  resources :email_templates

  resources :programs
  resources :positions
  resources :positions_helds

end

app/models/user.rb
class User < ApplicationRecord
  HONORIFICS = %w(
    Mr.
    Ms.
    Mrs.
    Dr.
  ).freeze

  # NOTE: privacy_settings column is an hstore in Postgres, which removes type
  # information and converts fields to string, thus false becomes "false" string.

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_many :email_templates, foreign_key: :author_id
  has_many :positions_held
  has_many :positions, through: :positions_held
  has_many :programs, through: :positions_held
  has_many :posts

  has_attached_file :profile_photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/missing.png"
  validates_attachment_content_type :profile_photo, content_type: /\Aimage\/.*\z/

  validates :salutation, inclusion: HONORIFICS
  validates :last_name,  presence: true
  validates :first_name, presence: true
  validates :email,
            uniqueness: {scope: [:last_name, :first_name]},
            allow_blank: true,
            :if => lambda {|attr| attr.present?}

  validates :last_name,
            uniqueness: {scope: [:first_name, :email]},
            allow_blank: true,
            :if => lambda {|attr| attr.present?}

  before_create do |user|
    if user.privacy_settings.empty?
      user.privacy_settings = {
        "personal"=>{"name"=>true, "email"=>true, "address"=>true, "phone"=>true},
        "social"=>{"facebook"=>true, "twitter"=>true, "instagram"=>true, "linked_id"=>true, "pinterest"=>true, "tumblr"=>true},
        "contact"=>{"solicitation"=>true, "emails"=>true, "phone_calls"=>true, "snail_mail"=>true},
        "camp"=>{"volunteer_info"=>true, "donor_info"=>true, "alumni_info"=>true, "counselor_info"=>true, "hospital_outreach_info"=>true}
      }
    end

    keys = ["personal", "social", "contact", "camp"]

    keys.each do |key|
      user.privacy_settings[key] ||= {}
    end
  end

  def friendly_name
    if nickname.present?
      nickname
    elsif first_name.present?
      first_name
    else
      "Friend"
    end
  end

  def years
    programs.map(&:years).flatten
  end

  def self.search(search)
    search.downcase!
    where("lower(first_name) LIKE ? OR lower(last_name) LIKE ? OR lower(maiden_name) LIKE ? OR lower(nickname) LIKE ? OR lower(email) LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    @years = (1992..2020).to_a.reverse!
    @positions = Position.order(:name)
    @users = User.includes(positions_held: [:program, :position]).
                  references(positions_held: [:program, :position])

    if params[:search].present?
        @users = @users.search(params[:search])
    end

    if params[:position].present?
        @users = @users.where("positions.name ilike '%#{params[:position]}%'")
    end

    if params[:year].present?
        @users = @users.select{|u| u.years.include?(params[:year].to_i)}
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: params[:id])
  end

  def edit
    @user = User.find(params[:user_id])
    ['personal', 'social', 'contact', 'camp'].each do |key|
        @user.privacy_settings[key] ||= {}
    end
  end

  def update
    @user = User.find(params[:user_id])

    if @user.update_attributes(user_params)
      redirect_to user_profile_path(@user), notice: 'User updated.'
    else
      render :edit, alert: 'Unable to update user.'
    end
  end

  def update_privacy
    @user = User.find(params[:user_id])
    @user.privacy_settings = ['personal', 'social', 'contact', 'camp'].reduce({}) do |h, key|
      temp = params[:preferences][key] || {}
      temp.each do |k,v|
        temp[k] = (v == "true")
      end
      h[key] = temp; h
    end

    if @user.save
      redirect_to edit_user_profile_path(@user)
    else
      raise 'hello'
    end
  end

  def list
    @years = (1992..2020).to_a.reverse!
    @positions = Position.order(:name)
    @users = User.includes(positions_held: [:program, :position]).
        references(positions_held: [:program, :position])

    if params[:search].present?
      @users = @users.search(params[:search])
    end

    if params[:position].present?
      @users = @users.where("positions.name ilike '%#{params[:position]}%'")
    end

    if params[:year].present?
      @users = @users.select{|u| u.years.include?(params[:year].to_i)}
    end
  end

  def import
    uploaded_file = params[:file]
    importer = UserImporter.new(uploaded_file.path.to_s)
    if importer.valid_headers?
      importer.import_by_row
      redirect_to grapevine_path
    else
      header_mismatch = importer.compare_headers
      flash[:error] = "Headers in spreadsheet do not match the expected layout. We expect: #{header_mismatch[:expected]}, and received #{header_mismatch[:actual]}"
      redirect_back(fallback_location: users_import_path)
    end
  end

  def upload
  end

  private

  def user_params
    params.require(:user).permit(
    :admin,
    :city,
    :country,
    :email,
    :facebook_username,
    :first_name,
    :instagram_username,
    :last_name,
    :linkedin_username,
    :maiden_name,
    :nickname,
    :password,
    :phone,
    :pinterest_name,
    :privacy_settings,
    :profile_photo_content_type,
    :profile_photo_file_name,
    :profile_photo_file_size,
    :profile_photo,
    :salutation,
    :state,
    :street_address,
    :tumblr_name,
    :twitter_handle,
    :zip_code,
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def display_name(user)
    name = user.first_name.to_s
    name += " \"#{user.nickname}\"" if user.nickname.present?
    name += " #{user.last_name}"
    name += " (fm. #{user.maiden_name})" if user.maiden_name.present?
    name
  end

  def display_city_state(user) 
    [user.city, user.state].select(&:present?).join(", ")
  end
end

app/views/users/_form.html.erb
<%= simple_form_for(@user, url: verification_path(@user)) do |f| %>
  <div class="row">
    <div class="col-6">
      <%= f.input :email %>
      <%= f.input :first_name %>
      <%= f.input :nickname %>
    </div>
    <div class="col-6">
      <%= f.input :salutation, collection: User::HONORIFICS, include_blank: false %>
      <%= f.input :last_name %>
      <%= f.input :maiden_name, label: "Maiden name (if different)" %>
    </div>
    <div class="col-6">
      <%= f.input :street_address %>
      <%= f.input :state %>
    </div>
    <div class="col-6">
      <%= f.input :city %>
      <%= f.input :zip_code %>
      <%= f.input :country, priority: ["US"] %>
    </div>
  </div>

  <div class="row">
    <div class="col-6">
      <%= f.input :facebook_username %>
      <%= f.input :twitter_handle %>
      <%= f.input :instagram_username %>
    </div>
    <div class="col-6">
      <%= f.input :linkedin_username %>
      <%= f.input :pinterest_name %>
      <%= f.input :tumblr_name %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 text-center">
      <br><br>
      <%= f.button :submit, "Verify Information", class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/users/_general.html.erb
<%= render "users/form" %>

<div class="preferences-navigation-footer">
  <%= link_to "Cancel", root_path, {class: 'btn btn-outline-danger', method: 'get'} %>
  <%= link_to "Skip to Photo", edit_user_profile_path(@user, state: 'photo'), {class: 'btn btn-outline-secondary', method: 'get'} %>
</div>

app/views/users/_new.html.erb
<%= simple_form_for(@user2) do |f| %>
  <%= f.error_notification %>



  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/_password.html.erb
<div class="password mx-auto">
  <%= simple_form_for(@user, url: verification_path(@user)) do |f| %>
    <%= f.input :password, label: 'New Password' %>
    <%= f.button :submit, "Save", class: "btn btn-block" %>
  <% end %>
</div>

<div class="preferences-navigation-footer">
  <%= link_to "Cancel", root_path, {class: 'btn btn-outline-danger', method: 'get'} %>
  <%= link_to "Skip to Privacy", edit_user_profile_path(@user, state: 'privacy'), {class: 'btn btn-outline-secondary', method: 'get'} %>
</div>

app/views/users/_positions_held.html.erb
<div class="grapevine-user-positions-helds">
  <% if user.positions_held.any? %>
    <ul>
      <% user.positions_held.each do |position_held| %>
        <% if current_user.admin? || current_user == user %>
          <li><%= link_to "#{position_held.name}", edit_positions_held_path(position_held) %></li>
        <% else %>
          <li><%= position_held.name %></li>
        <% end  %>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/users/_positions_held_form.html.erb
<%= render "positions_held", user: user %>

<div class="preferences-navigation-footer">
  <%= link_to "Cancel", root_path, {class: 'btn btn-outline-danger', method: 'get'} %>
  <%= link_to "New Position held", new_positions_held_path(user: user), {class: 'btn btn-success', method: 'get'} %>
  <%= link_to "Skip to Photo", edit_user_profile_path(user, state: 'photo'), {class: 'btn btn-outline-secondary', method: 'get'} %>
</div>

app/views/users/_privacy.html.erb
<div class="col-md-12 gallery-page-header">
  <h1>PRIVACY PREFERENCES</h1>
  <em>(checkmarks below indicate you ARE ok with sharing that info with other Orchard users)</em>
  <br><hr>
</div>

<%= form_for @user, url: update_user_privacy_path(@user) do |f| %>
  <div class="row col-md-12">
    <div class="col-md-6">
      <h3>Personal Info</h3>
      <% @personal_info_preferences = %i{name email address phone} %>
      <% @personal_info_preferences.each do |p| %>
        <div>
          <%= check_box_tag "preferences[personal][#{p}]", true, @user.privacy_settings['personal'][p.to_s] %>
          <%= label_tag p %>
        </div>
      <% end %>
    </div>

    <div class="col-md-6">
      <h3>Contact Preferences</h3>
      <% @contact_preferences = %i{ solicitation emails phone_calls snail_mail } %>
      <% @contact_preferences.each do |p| %>
        <div>
          <%= check_box_tag "preferences[contact][#{p}]", true, @user.privacy_settings['contact'][p.to_s] %>
          <%= label_tag p %>
        </div>
      <% end %>
    </div>

    <div class="col-md-6">
      <h3>Social Media</h3>
      <% @social_media_preferences = %i{facebook twitter instagram linked_id pinterest tumblr} %>
      <% @social_media_preferences.each do |p| %>
        <div>
          <%= check_box_tag "preferences[social][#{p}]", true, @user.privacy_settings['social'][p.to_s] %>
          <%= label_tag p %>
        </div>
      <% end %>
    </div>

    <div class="col-md-6">
      <h3>Camp Preferences</h3>
      <% @camp_preferences = %i{ volunteer_info donor_info alumni_info counselor_info hospital_outreach_info } %>
      <% @camp_preferences.each do |p| %>
        <div>
          <%= check_box_tag "preferences[camp][#{p}]", true, @user.privacy_settings['camp'][p.to_s] %>
          <%= label_tag p %>
        </div>
      <% end %>
    </div>

    <div class="preferences-navigation-footer">
      <%= f.submit "Update privacy preferences", class: "btn btn-primary" %>
      <%= link_to "Cancel", root_path, {class: 'btn btn-outline-danger', method: 'get'} %>
    </div>
  </div>
<% end %>

app/views/users/_search.html.erb
<% is_index = action_name == "index" %>
<form id="search-form" class="form-inline mb-2 justify-content-center" action="<%= is_index ? "/profiles" : "/users" %>" accept-charset="UTF-8" method="get">
 <div class="form-group">
   <label class="sr-only" for="exampleInputEmail1">Name</label>
   <div class="input-group mb-2 mr-sm-2 mb-sm-0">
     <input type="text" name="search" id="search" class="form-control" aria-describedby="search" placeholder="Name or Email">
  </div>
 </div>

 <div class="form-group mr-2">
   <label class="sr-only" for="years">Year</label>
   <select class="form-control" id="years" name="year">
     <option value=""></option>
     <%= years.each do |year| %>
        <option> <%= year %> </option>
     <% end %>
   </select>
 </div>
 <div class="form-group mr-2">
   <label class="sr-only" for="exampleSelect1">Position</label>
   <select class="form-control" id="positions" name="position">
     <option value=""></option>
     <%= positions.each do |position| %>
        <option> <%= position.name %> </option>
     <% end %>
   </select>
 </div>
 <button type="submit" class="btn btn-primary ml-2">Search</button>
<%= link_to 'Clear',
            is_index ? user_profiles_path : list_users_path,
            class: "btn btn-outline-success ml-2" %>
</form>

app/views/users/_social_media_buttons.html.erb
<div class="grapevine-social-buttons">
  <% if user.facebook_username.present? & user.privacy_settings["social"]["facebook"] %>
      <%= link_to("https://www.facebook.com/#{user.facebook_username}", target: "_blank", class: "btn") do %>
      <button class="btn">
        <i class="fa fa-facebook"></i>
      </button>
    <% end %>
  <% end %>

  <% if user.twitter_handle.present? & user.privacy_settings["social"]["twitter"] %>
    <%= link_to("https://www.twitter.com/#{user.twitter_handle}", target: "_blank", class: "btn") do %>
      <button class="btn">
        <i class="fa fa-twitter"></i>
      </button>
    <% end %>
  <% end %>

  <% if user.instagram_username.present? & user.privacy_settings["social"]["instagram"] %>
    <%= link_to("https://www.instagram.com/#{user.instagram_username}", target: "_blank", class: "btn") do %>
      <button class="btn">
        <i class="fa fa-instagram"></i>
      </button>
    <% end %>
  <% end %>

  <% if user.linkedin_username.present? & user.privacy_settings["social"]["linked_in"]  %>
    <%= link_to("https://www.linkedin.com/#{user.linkedin_username}", target: "_blank", class: "btn") do %>
      <button class="btn">
        <i class="fa fa-linkedin"></i>
      </button>
    <% end %>
  <% end %>

  <% if user.pinterest_name.present? & user.privacy_settings["social"]["pinterest"] %>
    <%= link_to("https://www.pinterest.com/#{user.pinterest_name}", target: "_blank", class: "btn") do %>
      <button class="btn">
        <i class="fa fa-pinterest"></i>
      </button>
    <% end %>
  <% end %>

  <% if user.tumblr_name.present? & user.privacy_settings["social"]["tumblr"] %>
    <%= link_to("https://www.tumblr.com/#{user.tumblr_name}", target: "_blank", class: "btn") do %>
      <button class="btn">
        <i class="fa fa-tumblr"></i>
      </button>
    <% end %>
  <% end %>

  <% if user.tumblr_name.present? %>
    <%= link_to("https://www.#{user.tumblr_name}tumblr.com", target: "_blank", class: "btn") do %>
      <button class="btn">
        <i class="fa fa-tumblr-square"></i>
      </button>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'layouts/nav' %>
<div class="preferences">
  <div class="gallery-page-header">
    <h1>
      <% if @user.privacy_settings["personal"]["name"] || @user == current_user || current_user.admin? %>
        Editing <%= @user.friendly_name %>'s profile
      <% end %>
      <% if current_user.admin? || current_user == @user %>
        <%= link_to '<button type="button" class="btn btn-secondary">View profile</button>'.html_safe, user_profile_path(current_user) %>
      <% end %>
    </h1>
  </div>

  <div class="preferences-stepper">
    <%= link_to edit_user_profile_path(current_user, state: 'general') do %>
      <%= image_tag("yellow-arrowhead.svg", class: params[:state].in?([nil, "general"]) ? "active" : "") %>
    <% end %>
    <%= link_to edit_user_profile_path(current_user, state: 'positions') do %>
      <%= image_tag("line-detail.svg", class: params[:state].in?([nil, "positions"]) ? "active" : "") %>
    <% end %>
    <%= link_to edit_user_profile_path(current_user, state: 'photo') do %>
      <%= image_tag("dark-green-arrowhead.svg", class: params[:state] == "photo" ? "active" : "") %>
    <% end %>
    <%= link_to edit_user_profile_path(current_user, state: 'password') do %>
      <%= image_tag("medium-green-arrowhead.svg", class: params[:state] == "password" ? "active" : "") %>
    <% end %>
    <%= link_to edit_user_profile_path(current_user, state: 'privacy') do %>
      <%= image_tag("light-green-arrowhead.svg", class: params[:state] == "privacy" ? "active" : "") %>
    <% end %>
  </div>

  <div class="preferences-form w-75 mx-auto">
    <% if params[:state] == 'privacy' %>
      <%= render "privacy" %>
    <% elsif params[:state] == 'photo' %>
      <%= render "photo" %>
    <% elsif params[:state] == 'password' %>
      <%= render "password" %>
    <% elsif params[:state] == 'positions' %>
      <h1>POSITIONS HELD</h1>
      <%= render "positions_held_form", user: @user %>
    <% else params[:state] == 'general' %>
      <%= render "general" %>
    <% end %>
  </div>

</div>

app/views/users/index.html.erb
<%= render 'layouts/nav' %>
<div class="grapevine-container">
  <div class="gallery-page-header">
    <h1 class="grapevine-title mb-4">The Grapevine</h1>
  </div>

  <div class="grapevine-search mb-4">
    <%= render 'search', years: @years, positions: @positions %>
  </div>
  <div class="list-group grapevine-user">
    <% if @users.blank? %>
      <h4>No profiles that matched your search of:</h4>
      <ul>
        <li><strong>Name or email:</strong> <%= params[:search].present? ? params[:search] : "---" %></li>
        <li><strong>Year:</strong> <%= params[:year].present? ? params[:year] : "---" %></li>
        <li><strong>Position:</strong> <%= params[:position].present? ? params[:position] : "---" %></li>
      </ul>
    <% else %>
      <% @users.each do |user| %>
        <div class="list-group-item list-group-item-action">
          <div class="col-md-12">
            <div class="grapevine-user-main">
              <div class="col-md-12">
                <%= link_to user_profile_path(user) do %>
                  <div class="grapevine-user-main-details">
                    <div class="grapevine-user-main-name">
                      <h3 class="mb-1 grapevine-user-name">
                        <%= display_name(user) if user.privacy_settings["personal"]["name"] || user == current_user || current_user.admin? %>
                        <% if current_user.admin? || current_user == user %>
                          <%= link_to '<button type="button" class="btn btn-secondary"><span class="fa fa-pencil"></span></button>'.html_safe,
                                      edit_user_profile_path(user),
                                      class: "edit-profile-button" %>
                        <% end %>
                      </h3>
                    </div>
                  </div>
                <% end %>
              </div>
              <div class="col-4">
                <%= link_to user_profile_path(user) do %>
                  <div class="grapevine-user-main-photo">
                    <%= image_tag(user.profile_photo) %>
                  </div>
                <% end %>
              </div>
              <div class="col-4">
                <div class="grapevine-user-main-info">
                  <li><%= user.phone if user.privacy_settings["personal"]["phone"] || user == current_user || current_user.admin? %></li>
                  <li><%= mail_to(user.email) if user.privacy_settings["personal"]["email"] || user == current_user || current_user.admin? %></li>
                  <% if user.privacy_settings["personal"]["address"] || user == current_user || current_user.admin? %>
                    <li><%= user.street_address %></li>
                    <li><%= display_city_state(user) %></li>
                    <li><%= user.country %></li>
                  <% end %>
                  <%= render 'social_media_buttons', user: user %>
                </div>
              </div>
              <div class="col-md-4">
                <%= render 'positions_held', user: user %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/list.html.erb
<%= render 'layouts/nav' %>

<div class="grapevine-container">
  <div class="gallery-page-header">
    <h1 class="grapevine-title mb-4"><%= User.model_name.human.pluralize %></h1>
  </div>

  <div class="grapevine-search mb-4">
    <%= render 'search', years: @years, positions: @positions %>
  </div>
  <div class="list-group grapevine-user">
    <% if @users.blank? %>
      <h4>No profiles that matched your search of:</h4>
      <ul>
        <li><strong>Name or email:</strong> <%= params[:search].present? ? params[:search] : "---" %></li>
        <li><strong>Year:</strong> <%= params[:year].present? ? params[:year] : "---" %></li>
        <li><strong>Position:</strong> <%= params[:position].present? ? params[:position] : "---" %></li>
      </ul>
    <% else %>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="panel panel-default panel-table">
              <div class="panel-body">
                <table class="table table-striped table-bordered table-list">
                  <thead>
                  <tr>
                    <th>User</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>City/state</th>
                    <th>Last login</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @users.each do | user | %>
                    <tr>
                      <td class="display-name"><%= link_to(display_name(user), edit_user_profile_path(user)) %></td>
                      <td class="<%= 'hidden-detail' if user.privacy_settings["personal"]["email"] %>"><%= user.email %></td>
                      <td class="<%= 'hidden-detail' if user.privacy_settings["personal"]["phone"] %>"><%= user.phone %></td>
                      <td class="<%= 'hidden-detail' if user.privacy_settings["personal"]["address"] %>"><%= display_city_state(user) %></td>
                      <td><%= user.last_sign_in_at && user.last_sign_in_at.to_date %></td>
                    </tr>
                  <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
        <p><%= link_to 'New user', root_path, class: "btn btn-primary" %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User2</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= render 'layouts/nav' %>
<div class="profile-container">
  <div class="profile-info">
    <div class="gallery-page-header">
      <h1>
        <% if @user.privacy_settings["personal"]["name"] || @user == current_user || current_user.admin? %>
          <%= @user.friendly_name %>'s Profile Page
        <% end %>
        <% if current_user.admin? || current_user == @user %>
          <%= link_to '<button type="button" class="btn btn-secondary"><span class="fa fa-pencil"></button>'.html_safe,
                      edit_user_profile_path(@user),
                      class: "edit-profile-button" %>
        <% end %>
      </h1>
    </div>

    <div class="list-group greenhouse-user">
      <div class="col-md-12">
        <div class="col-md-6">
          <div class="d-flex w-10 greenhouse-user-main">
            <%= image_tag(@user.profile_photo) %>
          </div>
        </div>
        <div class="col-md-6">
          <p class="mb-1">
          <h1>CONTACT INFO</h1>
          <% if @user.privacy_settings["personal"]["name"] || @user == current_user || current_user.admin? %>
            <br><%= display_name(@user) %>
          <% end %>
          <% if @user.privacy_settings["personal"]["address"] || @user == current_user || current_user.admin? %>
            <br><%= "#{@user.street_address}" %>
            <br><%= "#{@user.city}, #{@user.state} #{@user.country}" %>
          <% end %>
          <% if @user.privacy_settings["personal"]["email"] || @user == current_user || current_user.admin? %>
            <br><%= @user.email %>
          <% end %>
          <% if @user.privacy_settings["personal"]["phone"] || @user == current_user || current_user.admin? %>
            <br><%= @user.phone %>
          <% end %>
          <%= render 'social_media_buttons', user: @user %>
          <br>
          </p>
          <p class="mb-1">
          <h1>POSITIONS HELD</h1>
          <%= render 'positions_held', user: @user %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>