config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  get "/admin", to: "home#admin_panel", as: 'admin_panel'

  get "/profile/:id", to: "users#show", as: 'user_profile'
  get "/profile/:user_id/edit", to: "users#edit", as: 'edit_user_profile'

  post "/profile/:user_id/update", to: "users#update", as: 'update_user_profile'
  patch "/profile/:user_id/update_privacy", to: "users#update_privacy", as: 'update_user_privacy'
  get "/profiles", to: "users#index", as: 'user_profiles'
  get "/grapevine", to: "users#index", as: 'grapevine'

  get   "/users/:user_id/verify", to: "verification#edit"
  patch "/users/:user_id/verify", to: "verification#update", as: "verification"


  post '/posts/:post_id/comment', to: 'posts#comment', as: 'comment_post'
  get '/posts/hidden', to: 'posts#hidden', as: 'hidden_posts'
  post '/posts/:post_id/hide', to: 'posts#hide', as: 'hide_post'
  post '/posts/:post_id/unhide', to: 'posts#unhide', as: 'unhide_post'
  patch '/posts/:id/tags', to: 'posts#edit_tags', as: 'edit_post_tags'

  get "/users/upload", to: "users#upload", as: "upload_users"
  post "/users/import", to: "users#import"

  get 'tags/:tag', to: 'posts#index', as: :tag

  get "/users", to: "users#list", as: "list_users"

  devise_for :users
  resources :posts do
    get :autocomplete_tag_name, :on => :collection
  end

  resources :announcements
  resources :comments, only: [:update, :destroy]
  resources :email_templates

  resources :programs
  resources :positions
  resources :positions_helds

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.most_used(5)
    @announcements = Announcement.active

    if params[:tag]
      @photos = Post.hidden(false).tagged_with(params[:tag]).last(10)
    else
      @photos = Post.hidden(false).last(10)
    end

    @name = current_user.friendly_name
  end

  def admin_panel
    @user_count = User.all.length
    @active_user_count = User.where.not(last_sign_in_at: nil).all.length
    @announcement_count = Announcement.all.length
    @active_announcement_count = Announcement.active.length
    @program_count = Program.all.length
    @positions_count = Position.all.length
    @positions_held_count = PositionsHeld.all.length
    @greenhouse_post_count = Post.all.length
    @comment_count = Comment.all.length
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_announcements.html.erb
<% announcements_present = @announcements.any? %>

<div class="gallery-announcements <%= "active" if announcements_present %>">
  <h3><%= link_to("Announcements", announcements_path) %></h3>
  <% if announcements_present %>
    <ul class="gallery-announcements-list list-group">
      <% @announcements.each do |announcement| %>
        <li class="gallery-announcements-item list-group-item">
          <% if current_user.admin? %>
            <%= link_to announcement.text, edit_announcement_path(announcement) %>
          <% else %>
            <% announcement.text %>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% else %>
    No announcements
  <% end %>
</div>

app/views/home/_gallery.html.erb
<div class="gallery">
  <div class="gallery-linedetail">
  </div>

  <%= render 'announcements' %>

  <div class="gallery-container">
    <div class="gallery-left">
      <div class="gallery-photos">
        <h3><%= link_to 'The Greenhouse', posts_path %></h3>

      <div class="row">
        <%= form_tag(posts_path, :method => "get", id: "search-tags-form") do %>
          <%= text_field_tag :tag, params[:tag],
                             placeholder: "Search by tag",
                             class: "gallery-search-box" %>
          <%= submit_tag "Search", class: "btn btn-primary" %>
          <%= link_to 'Clear', posts_path, class: "btn btn-outline-success" %>
          <%= link_to "<span class='fa fa-plus'></span><span class='fa fa-camera'></span>".html_safe,
                      new_post_path,
                      class: "btn btn-outline-secondary gallery-additional-button" %>
          <%= link_to "Greenhouse viewer".html_safe,
                         post_path(Post.first),
                         class: "btn btn-outline-secondary gallery-additional-button" if Post.any? %>
        <% end %>
      </div>

        <div class="gallery-photos-tags">
          Filter by popular tags: <% @tags.each do |t| %>
            <%= link_to t.name, (root_path + "?tag=#{t.name}") %>
          <% end %>
        </div>
        <%= render 'photos' %>
      </div>
      <div class="gallery-socialFeed">
        <%= render 'social_feed' %>
      </div>
    </div>

    <div class="gallery-right">
      <div class="gallery-right-boxes">
        <h5><%= link_to "Calendar",
                        "https://www.doublehranch.org/calendar",
                        target: "_blank" %></h5>
        Check out our awesome upcoming events for Double H Ranch! <br />
        <%= link_to '<button type="button" class="btn btn-primary btn-block">Browse</button>'.html_safe,
                    'https://www.doublehranch.org/calendar',
                    target: "_blank" %>
      </div>
      <div class="gallery-right-boxes">
        <h5><%= link_to "Volunteer",
                        "https://www.doublehranch.org/volunteer",
                        target: "_blank" %></h5>
        Every set of hands make the work lighter and the applause louder.
        Whether you have a day, weekend, week or an entire summer,
        our camp offers a range of volunteer opportunities for you to make a difference
        by giving your time and talent.<br />
        <%= link_to '<button type="button" class="btn btn-primary btn-block">Apply</button>'.html_safe,
                    'https://www.doublehranch.org/volunteer',
                    target: "_blank" %>
      </div>
      <div class="gallery-right-boxes">
        <h5><%= link_to "Donate",
                        "https://www.doublehranch.org/donate", target: "_blank" %></h5>
        Your support is what enables us to continue providing our year-round programs to our campers.
        Together, there’s no telling how many lives we can touch and how many stories we can
        inspire as we continue to keep the promise to our campers that the
        Double H Ranch will be here forever. <br />
        <%= link_to '<button type="button" class="btn btn-primary btn-block">Donate</button>'.html_safe,
                    'https://www.doublehranch.org/donate',
                    target: "_blank" %>
      </div>
    </div>
  </div>
</div>

app/views/home/_photos.html.erb
<% @photos.each do | photo | %>
<div class="responsive">
  <div class="galleryimg">
      <%= link_to image_tag(photo.photo.url(:medium)), photo %>
  </div>
</div>
<% end %>
<div class="clearfix"></div>

app/views/home/_social_feed.html.erb
<div class="gallery-socialFeed-boxes gallery-twitter">
  <h5><%= link_to "Double H Ranch Twitter", "https://twitter.com/DoubleHRanch", target: "_blank" %></h5>
  <%= render 'social/twitter' %>
</div>
<div class="gallery-socialFeed-boxes gallery-facebook">
  <h5><%= link_to "Double H Ranch Facebook", "https://www.facebook.com/DoubleHRanchCamp/", target: "_blank" %></h5>
  <%= render 'social/facebook' %>
</div>

app/views/home/admin_panel.html.erb
<%= render 'layouts/nav' %>
<div class="home">
  <div class="home-hero">
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default panel-table">
        <div class="panel-heading">
          <div class="row">
            <div class="col col-xs-6">
              <div class="text-center gallery-page-header">
                <h3>Admin panel</h3>
              </div>
            </div>
          </div>
        </div>
        <div class="panel-body text-center">
          <table class="table table-striped table-bordered table-list">
            <thead>
            <tr>
              <th class="text-center">Record</th>
              <th class="text-center">Count</th>
              <th class="text-center"><em class="fa fa-cog"></em></th>
            </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= link_to(User.model_name.human.pluralize, list_users_path) %></td>
                <td><%= @user_count %> (active: <%= @active_user_count %>)</td>
                <td>
                  <%= link_to new_user_profile_path do %>
                    <i class="btn btn-primary" title="Create new"><em class="fa fa-plus"></em></i>
                  <% end %>

                  <%= link_to list_users_path do %>
                    <i class="btn btn-primary" title="View all"><em class="fa fa-bars"></em></i>
                  <% end %>

                  <%= link_to list_users_path do %>
                    <i class="btn btn-primary" title="Grapevine"><em class="fa fa-pagelines"></em></i>
                  <% end %>
                </td>
              </tr>

              <tr>
                <td><%= link_to(Post.model_name.human.pluralize, positions_helds_path) %></td>
                <td><%= @greenhouse_post_count %></td>
                <td>
                  <%= link_to new_post_path do %>
                    <i class="btn btn-primary" title="Create new"><em class="fa fa-plus"></em></i>
                  <% end %>

                  <%= link_to posts_path do %>
                    <i class="btn btn-primary" title="View all"><em class="fa fa-bars"></em></i>
                  <% end %>

                  <%= link_to list_users_path do %>
                    <i class="btn btn-primary" title="Grapevine"><em class="fa fa-pagelines"></em></i>
                  <% end %>
                </td>
              </tr>

              <tr>
                <td>Comments</td>
                <td><%= @comment_count %></td>
                <td></td>
              </tr>

              <tr>
                <td><%= link_to(Announcement.model_name.human.pluralize, announcements_path) %></td>
                <td><%= @announcement_count %> (active: <%= @active_announcement_count %>)</td>
                <td>
                  <%= link_to new_announcement_path do %>
                    <i class="btn btn-primary" title="Create new"><em class="fa fa-plus"></em></i>
                  <% end %>

                  <%= link_to announcements_path do %>
                    <i class="btn btn-primary" title="View all"><em class="fa fa-bars"></em></i>
                  <% end %>
                </td>
              </tr>

              <tr>
                <td><%= link_to(Program.model_name.human.pluralize, programs_path) %></td>
                <td><%= @program_count %></td>
                <td>
                  <%= link_to new_program_path do %>
                    <i class="btn btn-primary" title="Create new"><em class="fa fa-plus"></em></i>
                  <% end %>

                  <%= link_to programs_path do %>
                    <i class="btn btn-primary" title="View all"><em class="fa fa-bars"></em></i>
                  <% end %>
                </td>
              </tr>

              <tr>
                <td><%= link_to(Position.model_name.human.pluralize + "/Job Titles", positions_path) %></td>
                <td><%= @positions_count %></td>
                <td>
                  <%= link_to new_position_path do %>
                    <i class="btn btn-primary" title="Create new"><em class="fa fa-plus"></em></i>
                  <% end %>

                  <%= link_to positions_path do %>
                    <i class="btn btn-primary" title="View all"><em class="fa fa-bars"></em></i>
                  <% end %>
                </td>
              </tr>

              <tr>
                <td><%= link_to(PositionsHeld.model_name.human.pluralize, positions_helds_path) %></td>
                <td><%= @positions_held_count %></td>
                <td>
                  <%= link_to new_positions_held_path do %>
                    <i class="btn btn-primary" title="Create new"><em class="fa fa-plus"></em></i>
                  <% end %>

                  <%= link_to positions_helds_path do %>
                    <i class="btn btn-primary" title="View all"><em class="fa fa-bars"></em></i>
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= render 'layouts/nav' %>
<div class="home">
  <div class="home-hero">
    <div class="home-hero-user">
      <div class="home-hero-userpic">
        <% if current_user.profile_photo %>
          <%= image_tag(current_user.profile_photo.url) %>
        <% end %>
      </div>
      <div class="home-hero-username">
        <h1>Hi, <%= @name %>!</h1> <br />
          <%= link_to "<button type='button' class='btn btn-secondary'><span class='fa fa-pencil'></span></button>".html_safe,
                      edit_user_profile_path(current_user),
                      id: "edit-my-profile-button"
          %>
        <br />
      </div>
    </div>
  </div>
  <%= render 'gallery' %>
</div>