config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  get "/admin", to: "home#admin_panel", as: 'admin_panel'

  get "/profile/:id", to: "users#show", as: 'user_profile'
  get "/profile/:user_id/edit", to: "users#edit", as: 'edit_user_profile'

  post "/profile/:user_id/update", to: "users#update", as: 'update_user_profile'
  patch "/profile/:user_id/update_privacy", to: "users#update_privacy", as: 'update_user_privacy'
  get "/profiles", to: "users#index", as: 'user_profiles'
  get "/grapevine", to: "users#index", as: 'grapevine'

  get   "/users/:user_id/verify", to: "verification#edit"
  patch "/users/:user_id/verify", to: "verification#update", as: "verification"


  post '/posts/:post_id/comment', to: 'posts#comment', as: 'comment_post'
  get '/posts/hidden', to: 'posts#hidden', as: 'hidden_posts'
  post '/posts/:post_id/hide', to: 'posts#hide', as: 'hide_post'
  post '/posts/:post_id/unhide', to: 'posts#unhide', as: 'unhide_post'
  patch '/posts/:id/tags', to: 'posts#edit_tags', as: 'edit_post_tags'

  get "/users/upload", to: "users#upload", as: "upload_users"
  post "/users/import", to: "users#import"

  get 'tags/:tag', to: 'posts#index', as: :tag

  get "/users", to: "users#list", as: "list_users"

  devise_for :users
  resources :posts do
    get :autocomplete_tag_name, :on => :collection
  end

  resources :announcements
  resources :comments, only: [:update, :destroy]
  resources :email_templates

  resources :programs
  resources :positions
  resources :positions_helds

end

app/models/positions_held.rb
class PositionsHeld < ApplicationRecord
  belongs_to :user
  belongs_to :position, optional: true
  belongs_to :program, optional: true

  def name
    "#{position&.name} (#{program&.name})"
  end
end

app/controllers/positions_helds_controller.rb
class PositionsHeldsController < ApplicationController
  before_action :set_positions_held, only: [:show, :edit, :update, :destroy]

  # GET /positions_helds
  # GET /positions_helds.json
  def index
    @positions_helds = PositionsHeld.all
  end

  # GET /positions_helds/1
  # GET /positions_helds/1.json
  def show
  end

  # GET /positions_helds/new
  def new
    @positions_held = PositionsHeld.new
  end

  # GET /positions_helds/1/edit
  def edit
  end

  # POST /positions_helds
  # POST /positions_helds.json
  def create
    @positions_held = PositionsHeld.new(positions_held_params)

    respond_to do |format|
      if @positions_held.save
        format.html { redirect_to @positions_held, notice: 'Positions held was successfully created.' }
        format.json { render :show, status: :created, location: @positions_held }
      else
        format.html { render :new }
        format.json { render json: @positions_held.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions_helds/1
  # PATCH/PUT /positions_helds/1.json
  def update
    respond_to do |format|
      if @positions_held.update(positions_held_params)
        format.html { redirect_to @positions_held, notice: 'Positions held was successfully updated.' }
        format.json { render :show, status: :ok, location: @positions_held }
      else
        format.html { render :edit }
        format.json { render json: @positions_held.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions_helds/1
  # DELETE /positions_helds/1.json
  def destroy
    @positions_held.destroy
    respond_to do |format|
      format.html { redirect_to positions_helds_url, notice: 'Positions held was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_positions_held
      @positions_held = PositionsHeld.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def positions_held_params
      params.require(:positions_held).permit(:user_id, :position_id, :program_id)
    end
end

app/views/positions_helds/_form.html.erb
<%= simple_form_for(@positions_held) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user,
                      label_method: lambda { |user| display_name(user) },
                      collection: User.all.order(:last_name, :nickname, :first_name, :email),
                      selected: @positions_held.user_id || params[:user],
                      input_html: { value:  @positions_held.user_id || params[:user]}
    %>
    <%= f.association :position,
                      collection: Position.all.order(:name)  %>
    <%= f.association :program,
                      collection: Program.all.order(:name) %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <%#= link_to "New Position", new_position_path, {class: 'btn btn-outline-success', method: 'get'} %>
    <%#= link_to "View user's profile", edit_user_profile_path(f.object.user_id), class: "btn btn-optional" %>
  </div>
<% end %>

app/views/positions_helds/edit.html.erb
<%= render 'layouts/nav' %>

<div class="gallery-page-header">
  <h1>Editing Positions Held</h1>
</div>

<%= render 'form', positions_held: @positions_held %>

<%= link_to 'Back', positions_helds_path %>

app/views/positions_helds/index.html.erb
<%= render 'layouts/nav' %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default panel-table">
        <div class="panel-heading">
          <div class="row">
            <div class="col col-xs-6">
              <div class="text-center gallery-page-header">
                <h3><%= PositionsHeld.model_name.human.pluralize %></h3>
              </div>
            </div>
          </div>
        </div>
        <div class="panel-body text-center">
          <table class="table table-striped table-bordered table-list">
            <thead>
            <tr>
              <th>User</th>
              <th>Position</th>
              <th>Program</th>
              <th class="text-center"><em class="fa fa-cog"></em></th>
            </tr>
            </thead>
            <tbody>
            <% @positions_helds.each do | positions_held | %>
              <tr>
                <td class="text-left"><%= display_name(positions_held.user) %></td>
                <td class="text-left"><%= positions_held.position.name if positions_held.position %></td>
                <td class="text-left"><%= positions_held.program.name if positions_held.program %></td>
                <td align="center">
                  <%= link_to edit_positions_held_path(positions_held) do %>
                    <i class="btn btn-primary"><em class="fa fa-pencil"></em></i>
                  <% end %>

                  <%= link_to positions_held_path(positions_held), method: :delete do %>
                    <i class="btn btn-outline-danger"><em class="fa fa-trash"></em></i>
                  <% end %>

                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <p><%= link_to 'New position held', new_positions_held_path, class: "btn btn-primary" %></p>
</div>

app/views/positions_helds/new.html.erb
<%= render 'layouts/nav' %>

<div class="gallery-page-header">
  <h1>New Positions Held</h1>
</div>

<%= render 'form', positions_held: @positions_held %>

<%= link_to 'Back', positions_helds_path %>

app/views/positions_helds/show.html.erb
<%= render 'layouts/nav' %>

<p>
  <strong>User:</strong>
  <%= @positions_held.user.friendly_name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @positions_held.position.name if @positions_held.position %>
</p>

<p>
  <strong>Program:</strong>
  <%= @positions_held.program.name if @positions_held.program %>
</p>

<%= link_to 'Edit', edit_positions_held_path(@positions_held) %> |
<%= link_to 'Back', positions_helds_path %>