config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  get "/admin", to: "home#admin_panel", as: 'admin_panel'

  get "/profile/:id", to: "users#show", as: 'user_profile'
  get "/profile/:user_id/edit", to: "users#edit", as: 'edit_user_profile'

  post "/profile/:user_id/update", to: "users#update", as: 'update_user_profile'
  patch "/profile/:user_id/update_privacy", to: "users#update_privacy", as: 'update_user_privacy'
  get "/profiles", to: "users#index", as: 'user_profiles'
  get "/grapevine", to: "users#index", as: 'grapevine'

  get   "/users/:user_id/verify", to: "verification#edit"
  patch "/users/:user_id/verify", to: "verification#update", as: "verification"


  post '/posts/:post_id/comment', to: 'posts#comment', as: 'comment_post'
  get '/posts/hidden', to: 'posts#hidden', as: 'hidden_posts'
  post '/posts/:post_id/hide', to: 'posts#hide', as: 'hide_post'
  post '/posts/:post_id/unhide', to: 'posts#unhide', as: 'unhide_post'
  patch '/posts/:id/tags', to: 'posts#edit_tags', as: 'edit_post_tags'

  get "/users/upload", to: "users#upload", as: "upload_users"
  post "/users/import", to: "users#import"

  get 'tags/:tag', to: 'posts#index', as: :tag

  get "/users", to: "users#list", as: "list_users"

  devise_for :users
  resources :posts do
    get :autocomplete_tag_name, :on => :collection
  end

  resources :announcements
  resources :comments, only: [:update, :destroy]
  resources :email_templates

  resources :programs
  resources :positions
  resources :positions_helds

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  acts_as_commentable
  acts_as_taggable_on :tags

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  validates_attachment_presence :photo

  scope :hidden, -> (hidden) { where('hide = ?', hidden) }

  def next
    self.class.where("id > ?", id).first
  end

  def previous
    self.class.where("id < ?", id).last
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy, :edit_tags]
  autocomplete :tag, :name, :class_name => 'ActsAsTaggableOn::Tag'


  def index
    @tags = ActsAsTaggableOn::Tag.most_used(5)
    if params[:tag]
      tagged = Post.tagged_with(params[:tag])
      @posts = tagged.hidden(false)
    else
      @posts = Post.hidden(false)
    end
  end

  def show
    @post = Post.includes(comments: [:user]).find(params[:post_id] || params[:id])
    @comment = Comment.new(commentable_type: 'Post', commentable_id: @post.id, user: current_user)
  end

  def new
    @post = Post.new
  end

  def create
    post_attrs = post_params.clone
    post_attrs[:user_id] = current_user.id
    photos = post_attrs.delete(:photos) || []

    posts = photos.map do |photo|
      Post.new(post_attrs.merge({ photo: photo }))
    end

    saved = ActiveRecord::Base.transaction do
      posts.map {|p| p.save }.all?
    end

    saved = false if posts.empty?

    if saved
      redirect_to posts_path, notice: 'Post was successfully created'
    else
      @post = Post.new(post_attrs)
      @post.valid?
      render :new
    end
  end

  def destroy
    @post.delete
    redirect_to posts_path
  end

  def edit

  end

  def update
    @post.update(caption: params[:caption])
    redirect_to post_path(@post)
  end

  def comment
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.commentable_id = params[:post_id]
    @comment.commentable_type = 'Post'

    if @comment.save
      redirect_to post_path(@comment.commentable_id), notice: 'Comment was successfully created'
    else
      render post_path(@comment.commentable_id)
    end
  end

  def hidden
      @posts = Post.hidden(true)
  end

  def hide
      post = Post.find(params[:post_id])
      post.update(hide: true)
      redirect_to posts_path, notice: 'Post hidden.'
  end

  def unhide
      post = Post.find(params[:post_id])
      post.update(hide: false)
      redirect_to posts_path, notice: 'Post is no longer hidden.'
  end

  def edit_tags
    @post.tag_list = params[:post][:tag_list]
    if @post.save
      redirect_to post_path(@post), notice: 'Tags were successfully updated'
    else
      redirect_to post_path(@post), notice: 'Tags were unable to update'
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(
      :caption,
      :tag_list,
      :user_id,
      photos: [],
    )
  end

  def comment_params
    params.require(:comment).permit(
      :comment,
      :commentable_id,
      :commentable_type,
    )
  end
end

app/views/posts/_comment_form.html.erb
<h5> Write a comment </h5>
<%= form_for(@comment, url: comment_post_path(@comment.commentable_id)) do |f| %>
  <%= f.text_area :comment, cols: 20, rows: 5 %>
  <br />
  <%= f.submit 'Submit', class: 'btn btn-primary'  %>
<% end %>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @post, html: { multipart: true } do |f| %>
  <%= f.file_field :photos, multiple: 'multiple', required: true %> <br /><br />
  <%= f.label :caption %>
  <%= f.text_field :caption %> <br /><br />
  <%= f.label :tag_list, "Tags (comma separated)" %>
  <%= f.text_field :tag_list, value: f.object.tag_list.to_s %> <br /><br />
  <%= f.submit "Create #{Post.model_name.human.capitalize}", class: 'btn btn-primary btn-block' %>
<% end %>

app/views/posts/_tag_form.html.erb
<%= form_for(@post, url: edit_post_tags_path(@post)) do |f| %>
  <%= f.text_field :tag_list, value: f.object.tag_list.to_s %>
  <%= f.submit 'Edit Tags', class: 'btn btn-outline-success'  %>
<% end %>

app/views/posts/edit.html.erb
<%= render 'layouts/nav' %>
<div class="upload-container">
  <div class="gallery-page-header">
    <h3>Edit your Post Caption</h3>
  </div>
  <br />
  <%= form_tag post_path(@post), method: "put" do %>
    <%= text_area_tag :caption, @post.caption %><br>
    <%= submit_tag "Submit Edits" %>
  <% end %>
</div>

app/views/posts/hidden.html.erb
<%= render 'layouts/nav' %>

<div class="gallery-page-header">
  <h1>Hidden Posts</h1>
</div>

<%= link_to "Back to displayed #{Post.model_name.human.pluralize}", posts_path if current_user.admin? %>

<% @posts.each do |post| %>
    <p><%= link_to (image_tag post.photo.url(:thumb)), post_path(post) %></p>
    <p><%= link_to post.caption, post_path(post) %></p>
    <p><%= link_to 'Unhide', unhide_post_path(post.id), method: :post if current_user.admin? %></p>
<% end %>

app/views/posts/index.html.erb
<%= render 'layouts/nav' %>
<div class="gallery-photos">

  <div class="text-center gallery-page-header">
    <h3><%= Post.model_name.human.pluralize %></h3>
  </div>

  <div class="row">
    <%= form_tag(posts_path, :method => "get", id: "search-tags-form") do %>
      <%= text_field_tag :tag,
                         params[:tag],
                         placeholder: "Search by tag",
                         class:"gallery-search-box" %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
      <%= link_to 'Clear', posts_path, class: "btn btn-outline-success" %>
    <% end %>
    <p><%= link_to "<span class='fa fa-plus'></span><span class='fa fa-camera'></span>".html_safe,
                  new_post_path,
                  class: "btn btn-outline-secondary gallery-additional-button" %></p>
    <% if current_user.admin? %>
      <p><%= link_to "Manage hidden",
                     hidden_posts_path,
                     class: "btn btn-outline-warning gallery-additional-button" %></p>
    <% end %>
    <p><%= link_to "Greenhouse viewer".html_safe,
                   post_path(Post.first),
                   class: "btn btn-outline-secondary gallery-additional-button" if Post.any? %></p>
  </div>

  <div class="gallery-photos-tags">
      Filter by popular tags: <% @tags.each do |t| %>
          <%= link_to t.name, (root_path + "?tag=#{t.name}") %>
      <% end %>
  </div>

  <% @posts.each do | post | %>
  <div class="responsive">
      <div class="galleryimg text-center">
          <%= link_to image_tag(post.photo.url(:medium)), post %>
          <%= link_to post.caption, post_path(post) %></p>
          <% if post.tags.any? %>
            <p>Tags: <%= raw(post.tag_list.map { |t| link_to t, tag_path(t)  }.join(', ')) %></p>
          <% end %>
          <% if current_user.admin? %>
              <p><%= link_to 'Hide', hide_post_path(post.id), method: :post, class: "btn btn-warning" %></p>
          <% end %>
          </a>
      </div>
  </div>
  <% end %>
  <div class="clearfix"></div>
</div>

app/views/posts/new.html.erb
<%= render 'layouts/nav' %>
<div class="upload-container">
  <div class="gallery-page-header">
    <h3>Upload a Photo</h3>
  </div>
  <br />
  <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<%= render 'layouts/nav' %>
<div class="post-container">
  <div class="gallery-page-header">
    <h1>
      GREENHOUSE VIEWER
      <%= link_to 'Back to Greenhouse', posts_path, class: "btn btn-outline-secondary" %>
    </h1>
    <div class="post-navigation">
      <%= link_to 'Previous', post_path(@post.previous), class: "btn btn-outline-secondary" if @post.previous %>
      <%= link_to 'Next', post_path(@post.next), class: "btn btn-outline-secondary" if @post.next %>
    </div>
  </div>

  <div class="row col-md-12">
    <div class="col-md-8">
      <%= image_tag @post.photo.url %>
      <!--<div class="col-md-4">-->
      <div class="text-center page-header">
        <span class="post-tags">
          <span class="post-tags">
            <h5>
              TAGS:
              <%= raw(@post.tag_list.map { |t| link_to t, tag_path(t)  }.join(', ')) %>
            </h5>

          </span>
          <hr>
          <div class="post-tag-form">
            <%= render 'tag_form' %>
          </div>
          <hr>
          <div class="actions">
            <%= link_to 'Hide', hide_post_path(@post), method: :post, class:'btn btn-warning' if current_user.admin? %>
            <%= link_to "Delete", @post, method: :delete, class: "btn btn-outline-danger" if (current_user.admin? || @post.user == current_user) && @post.comments.none? %>
          </div>
        </span>
      </div>
    <!--</div>-->
    </div>
    <div class="col-md-4">
      <div class="post-caption">
        <h5>
          <strong><%= link_to("CAPTION: " + @post.caption, edit_post_path(@post), id: "edit-caption") %></strong>
        </h5>
        <hr>
      </div>
      <div class="post-comments">
        <% if @post.comments.any? %>
          <h5>COMMENTS</h5>
          <%= render @post.comments %>
          <hr><br>
        <% end %>
        <div class="post-comments-form">
          <%= render 'comment_form' %>
        </div>
      </div>
    </div>
  </div>
</div>